---
- name: Gather CPU RAM and Disk Space Usage
  hosts: all
  gather_facts: yes
  tasks:
    - name: Gather CPU usage
      shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2}'
      register: cpu_usage

    - name: Gather RAM Usage
      shell: top -bn1 | awk '/MiB Mem/ {printf "%.2f\n", $8/$4 * 100}'
      register: ram_usage

    - name: Gather Disk Space Usage
      shell: "df -h / | awk 'NR==2{print $3}'"
      register: disk_used

    - name: Gather Total Disk Space
      shell: "df -h / | awk 'NR==2{print $2}'"
      register: disk_total

    - name: Calculate Total Disk Space Used (%)
      set_fact:
        disk_space_used_percent: "{{ (disk_used.stdout | int / disk_total.stdout | int) * 100 | round(2) }}"

    - name: Usage Stats
      debug:
        msg: 
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "CPU Usage: {{ cpu_usage.stdout }}%"
          - "RAM Usage: {{ ram_usage.stdout }}%"
          - "Disk Space Used: {{ disk_used.stdout }}"
          - "Total Disk Space: {{ disk_total.stdout }}"
          - "Total Disk Space Used (%): {{ disk_space_used_percent }}%"
