---
- name: Get System Time
  hosts: all
  become: no  # No need for privilege escalation for fetching system time

  tasks:
    - name: Fetch System Time
      command: date
      register: system_time_result

    - name: Display System Time
      debug:
        var: system_time_result.stdout_lines
