---
- name: Shutdown Ubuntu Server
  hosts: all
  become: yes

  tasks:
    - name: Ensure the system is up-to-date
      apt:
        update_cache: yes

    - name: Shutdown the server
      command: /sbin/shutdown -h now
