---
- name: Shutdown Ubuntu Server
  hosts: all
  become: true

  tasks:
    - name: Ensure the system is up-to-date
      apt:
        update_cache: yes

    - name: Delay for 10 seconds before shutdown
      command: sleep 10

    - name: Shutdown the server
      command: /sbin/shutdown -h now
