---
- name: Shutdown all Ubuntu servers
  hosts: all
  become: yes  # This enables privilege escalation (sudo)

  tasks:
    - name: Shut down the servers
      shutdown:
        msg: "Shutting down the system"
        state: poweredoff
      become: yes
