---
- name: Shutdown all Ubuntu servers
  hosts: all
  become: yes  # This enables privilege escalation (sudo)

  tasks:
    - name: Shut down the servers
      shell: shutdown -h now
      become: yes
      register: shutdown_result

    - name: Display shutdown command output
      debug:
        var: shutdown_result.stdout_lines
