---
- name: Restart Ubuntu Servers
  hosts: all
  become: yes

  tasks:
    - name: Ensure all packages are up to date
      apt:
        update_cache: yes

    - name: Restart the server
      command: shutdown -r now